language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mysql $* <<EOF
DROP DATABASE IF EXISTS activatoradmin;
CREATE DATABASE activatoradmin;
CREATE TABLE items (id INT(11) NOT NULL AUTO_INCREMENT, isactive TINYINT(4), name VARCHAR(255), image VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id));
CREATE TABLE items_test (id INT(11) NOT NULL AUTO_INCREMENT, isactive TINYINT(4), name VARCHAR(255), image VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id));

EOF

script: phpunit test/phpunit/
