language: node_js

node_js:
  - "0.10.28"

before_install: npm install -g grunt-cli

install: npm install

before_script:
  - sh -c "mysql -e 'CREATE DATABASE activatoradmin;'"
  - sh -c "mysql -u root -e 'USE activatoradmin; CREATE TABLE IF NOT EXISTS items (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, isactive TINYINT(4), name VARCHAR(255), image VARCHAR(255) DEFAULT NULL) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;'"
  - sh -c "mysql -u root -e 'USE activatoradmin; CREATE TABLE IF NOT EXISTS items_test (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, isactive TINYINT(4), name VARCHAR(255), image VARCHAR(255) DEFAULT NULL) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;'"

script: grunt travis
