language: php

php:
  - 7.0
  - 7.1

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" = 5.* ]]; then echo 'extension = "mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;

install:
   - composer require global phpunit/phpunit:6.3.0

before_script:
  - composer install
  - sh -c "mysql -e 'CREATE DATABASE activatoradmin;'"
  - sh -c "mysql -u root -e 'USE activatoradmin; CREATE TABLE IF NOT EXISTS items (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, isactive TINYINT(4), name VARCHAR(255), image VARCHAR(255) DEFAULT NULL) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;'"
  - sh -c "mysql -u root -e 'USE activatoradmin; CREATE TABLE IF NOT EXISTS items_test (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, isactive TINYINT(4), name VARCHAR(255), image VARCHAR(255) DEFAULT NULL) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;'"

services: mongodb

script: phpunit test/phpunit/
