language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mysql -e 'CREATE DATABASE activatoradmin;'
  - mysql -e 'CREATE TABLE items (id INT(11) NOT NULL AUTO_INCREMENT, isactive TINYINT(4), name VARCHAR(255), image VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id));'
  - mysql -e 'CREATE TABLE items_test (id INT(11) NOT NULL AUTO_INCREMENT, isactive TINYINT(4), name VARCHAR(255), image VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id));'

script: phpunit test/phpunit/
